// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHOYzNb9sJJgyHNNSX4EnZ7oIytBKlcXE',
    appId: '1:198847538378:web:5997c270b32bd7e2208033',
    messagingSenderId: '198847538378',
    projectId: 'gamegate-d32b6',
    authDomain: 'gamegate-d32b6.firebaseapp.com',
    storageBucket: 'gamegate-d32b6.firebasestorage.app',
    measurementId: 'G-S6ZLNC7Q2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLNU-C-TjyKb3JF_Hqyac7RWU3-5nHlPY',
    appId: '1:198847538378:android:112782d6f7ffe2db208033',
    messagingSenderId: '198847538378',
    projectId: 'gamegate-d32b6',
    storageBucket: 'gamegate-d32b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9eR8INuoYw596TbpzDQ-n1TFhTkBObOc',
    appId: '1:198847538378:ios:ac0987a44f9b8c4e208033',
    messagingSenderId: '198847538378',
    projectId: 'gamegate-d32b6',
    storageBucket: 'gamegate-d32b6.firebasestorage.app',
    iosBundleId: 'com.example.gameGate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9eR8INuoYw596TbpzDQ-n1TFhTkBObOc',
    appId: '1:198847538378:ios:ac0987a44f9b8c4e208033',
    messagingSenderId: '198847538378',
    projectId: 'gamegate-d32b6',
    storageBucket: 'gamegate-d32b6.firebasestorage.app',
    iosBundleId: 'com.example.gameGate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHOYzNb9sJJgyHNNSX4EnZ7oIytBKlcXE',
    appId: '1:198847538378:web:fcc15b74ef6e211f208033',
    messagingSenderId: '198847538378',
    projectId: 'gamegate-d32b6',
    authDomain: 'gamegate-d32b6.firebaseapp.com',
    storageBucket: 'gamegate-d32b6.firebasestorage.app',
    measurementId: 'G-0369MCLRSP',
  );
}
